# Font Configuration
font_size 14.0

# font_family         UbuntuMono Nerd Font
# bold_font           UbuntuMono Nerd Font
# bold_italic_font    UbuntuMono Nerd Font
# italic_font         UbuntuMono Nerd Font
# font_family         Fira Code
# bold_font           Fira Code
# bold_italic_font    Fira Code
# italic_font         Fira Code
# Window Configuration
window_padding_width 12
background_opacity 0.80
# background_blur 32
hide_window_decorations yes

# Cursor Configuration
cursor_shape block
cursor_blink_interval 1

# Scrollback
scrollback_lines 3000

# Terminal features
copy_on_select yes
strip_trailing_spaces smart

# Key bindings for common actions
# map ctrl+shift+n new_window
map ctrl+shift+t new_tab
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0
# atajos desde mi propia configuración de kitty
map ctrl+shift+j  next_window
map ctrl+shift+k  previous_window
map ctrl+shift+n  set_tab_title
map ctrl+shift+l  next_tab
map ctrl+shift+h  previous_tab

# Tab configuration
tab_bar_style powerline
tab_bar_align left

# Shell integration
shell_integration enabled

# Dank color generation
include dank-tabs.conf
include dank-theme.conf


# BEGIN_KITTY_FONTS
font_family      family="MonaspiceAr Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
